package domain

import "errors"

var (
	ErrInvalidArgument               = errors.New("invalid argument")
	ErrUnauthorized                  = errors.New("unauthorized")
	ErrForbidden                     = errors.New("forbidden")
	ErrNotFound                      = errors.New("not found")
	ErrGameSessionFinished           = errors.New("game session finished")
	ErrScoreTotalMustBeZero          = errors.New("score total must be zero")
	ErrInvalidPlayer                 = errors.New("invalid player")
	ErrPlayerAlreadyExists           = errors.New("player already exists")
	ErrGameMemberRequired            = errors.New("game member required")
	ErrConflict                      = errors.New("conflict")
	ErrActiveGameExists              = errors.New("active game exists")
	ErrGameSessionVoided             = errors.New("game session voided")
	ErrGameCapacityFull              = errors.New("game capacity full")
	ErrCannotLeaveWithNonZeroScore   = errors.New("cannot leave with non-zero score")
	ErrParticipantRequired           = errors.New("participant required")
	ErrParticipantInactive           = errors.New("participant inactive")
	ErrDuplicateDisplayName          = errors.New("duplicate display name")
	ErrInvalidScoreTransferAmount    = errors.New("invalid score transfer amount")
	ErrScoreTransferReceiverRequired = errors.New("score transfer receiver required")
	ErrIdempotencyKeyRequired        = errors.New("idempotency key required")
	ErrIdempotencyConflict           = errors.New("idempotency conflict")
	ErrFinishRequestPending          = errors.New("finish request pending")
	ErrFinishRequestNotPending       = errors.New("finish request not pending")
	ErrOwnerRequired                 = errors.New("owner required")
	ErrPublicShareUnavailable        = errors.New("public share unavailable")
	ErrAlreadyDeactivated            = errors.New("player already deactivated")
	ErrNotOwner                      = errors.New("not owner")
	ErrFinishRequestNotFound         = errors.New("finish request not found")
	ErrGameSessionActive             = errors.New("game session active")
	ErrExternalServiceFailed         = errors.New("external service failed")
)
